In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from function import load_restaurants_data
import seaborn as sns

In [3]:
restaurants, restaurants_employment = load_restaurants_data(path='../data/London_in_depth/')

In [4]:
restaurants

,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
area,,,,,,,,,,,,,,,,,
London,5455,5525,5540,5575,5915,5940,6175,5985,5910,6175,6210,6655,6715,7035,7515,7745,7990
City of London,180,190,190,175,180,170,205,185,180,195,190,205,230,255,270,270,295
Barking and Dagenham,30,30,30,35,35,35,35,35,30,30,30,40,40,35,45,40,35
Barnet,205,195,200,200,200,200,205,195,210,215,205,235,250,240,255,245,270
Bexley,85,80,75,80,85,95,95,95,90,95,95,105,105,105,100,110,110
Brent,120,125,130,120,125,145,155,140,145,150,155,165,170,165,185,200,190
Bromley,145,150,150,155,165,175,165,165,170,175,160,180,185,180,180,190,200
Camden,445,425,405,405,445,430,440,415,410,440,445,465,480,510,565,570,600
Croydon,145,150,160,155,165,170,175,160,160,155,170,165,155,155,175,185,205
Ealing,145,155,160,155,155,150,165,165,160,165,160,175,165,175,190,190,190
Enfield,120,115,115,125,115,130,135,130,125,130,140,135,125,135,155,155,150
Greenwich,70,75,65,75,70,75,90,95,90,100,100,120,125,120,125,140,145
Hackney,95,100,100,110,110,120,120,130,120,125,140,160,165,180,230,245,285
Hammersmith and Fulham,175,165,180,195,200,205,205,200,195,215,230,240,225,255,260,265,270
Haringey,105,100,105,105,120,120,120,120,115,115,110,120,120,130,160,175,175
Harrow,100,100,110,110,125,125,135,130,135,135,145,150,140,155,155,155,150
Havering,75,75,80,75,95,90,90,105,110,115,100,105,105,110,125,125,130
Hillingdon,130,130,145,130,140,130,135,130,125,140,135,150,150,160,160,155,165
Hounslow,90,90,85,90,105,110,115,120,115,115,110,125,125,130,145,140,150
Islington,205,210,210,215,235,245,250,245,245,245,250,270,270,280,320,340,370
Kensington and Chelsea,370,380,365,370,375,350,365,330,345,375,360,365,375,375,385,400,400
Kingston upon Thames,90,90,95,90,100,110,110,110,110,105,100,115,105,110,115,120,120
Lambeth,160,170,175,175,185,185,190,195,175,180,180,210,215,255,260,285,295
Lewisham,70,80,80,80,90,90,90,85,90,90,90,105,95,110,120,140,130
Merton,105,100,100,105,115,110,115,100,100,105,100,120,115,105,115,115,120
Newham,45,55,50,60,75,85,85,80,75,80,75,95,110,110,120,120,125
Redbridge,95,90,85,100,105,110,115,115,115,110,115,120,110,125,120,130,130
Richmond upon Thames,175,195,180,195,205,190,180,175,175,195,180,195,190,190,200,185,195
Southwark,130,135,145,140,165,175,180,185,180,180,185,190,215,230,265,270,295
Sutton,85,80,80,75,80,80,90,95,95,85,80,85,85,90,95,90,95
Tower Hamlets,135,160,165,175,175,180,200,195,210,215,215,245,260,285,300,320,320
Waltham Forest,75,70,65,65,85,80,85,80,65,75,80,95,95,95,115,125,135
Wandsworth,210,220,215,220,235,245,240,225,230,245,240,235,240,285,270,280,275
Westminster,1055,1045,1030,1015,1065,1030,1095,1050,1005,1085,1130,1170,1170,1195,1230,1260,1270

In [5]:
restaurants_employment

,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
area,,,,,,,,,,,,,,,,,
London,63800,69800,70900,69100,71400,71400,71500,68300,71100,79000,83600,90700,95300,104000,112800,118600,124500
City of London,2400,2900,3100,2900,3000,2900,3100,2800,2900,3200,3200,3700,4200,5200,5900,6700,6800
Barking and Dagenham,300,300,300,300,300,300,300,300,200,300,300,300,300,300,300,400,300
Barnet,1600,1600,1600,1500,1500,1500,1700,1400,2100,2300,1700,1800,2100,2200,2400,2400,2900
Bexley,800,800,800,800,700,800,800,600,600,700,800,800,800,800,800,1000,1000
Brent,800,1200,1100,900,700,800,900,800,1000,1000,1300,1500,1400,1500,1700,1900,1900
Bromley,1400,1500,1700,1500,1500,1600,1600,1400,1400,1400,1500,1800,1800,1800,2200,2200,2200
Camden,5000,5300,5300,4900,4900,5100,4700,4400,5000,5300,5700,6500,7100,7800,9100,9400,10200
Croydon,1300,1300,1500,1300,1300,1300,1500,1500,1400,1300,1600,1500,1500,1500,1600,1600,1800
Ealing,1200,1200,1200,1500,1200,1100,1100,1100,1000,1900,2000,2000,1800,1600,1900,1800,1900
Enfield,1100,1100,1100,1100,1000,1000,1000,1000,900,900,1100,1100,1000,1100,1300,1300,1300
Greenwich,700,700,600,700,800,700,800,700,800,1000,1200,1500,1700,1500,1700,1900,2000
Hackney,600,600,800,900,900,1000,900,1100,1200,1400,1800,2100,2300,2700,3700,4000,4700
Hammersmith and Fulham,1400,1700,1800,1700,1900,1800,1900,1800,1900,2300,2700,3100,3100,3400,3500,3500,3700
Haringey,600,600,800,800,900,800,800,700,800,700,800,900,900,1200,1300,1500,1400
Harrow,900,1000,1000,1000,1000,900,1000,900,900,1000,1100,1200,1100,1300,1400,1200,1400
Havering,800,700,900,800,1000,800,900,900,1300,1300,1100,1200,1300,1100,1200,1500,1400
Hillingdon,1700,1600,2100,2000,1900,1800,1900,1800,1800,2200,2400,2600,2700,2700,2500,2600,2900
Hounslow,800,800,800,800,800,900,900,1000,1100,1100,1100,1300,1300,1400,1400,1400,1600
Islington,2000,2100,1900,1900,2300,2300,2500,2500,2600,2800,2800,3200,3300,3600,4700,4500,5000
Kensington and Chelsea,5200,6400,5900,6000,6000,5700,5700,5300,5700,6200,6300,6700,7100,7100,7400,7500,7700
Kingston upon Thames,1100,1000,1200,1100,1300,1600,1300,1200,1200,1100,1100,1300,1300,1400,1400,1500,1600
Lambeth,1800,2200,2100,2100,2000,1800,1500,1600,1800,2100,2200,2500,2700,3400,3600,3900,4100
Lewisham,500,600,600,500,500,600,600,600,600,700,800,1000,900,900,1000,1100,1100
Merton,800,800,800,900,1000,900,1000,800,900,1000,1100,1200,1200,1300,1400,1400,1500
Newham,400,500,500,600,500,700,700,700,700,900,900,1100,1600,2200,2300,2400,2300
Redbridge,800,700,700,800,900,900,900,800,800,900,1000,1000,1000,1000,1200,1200,1200
Richmond upon Thames,1500,1700,1600,1600,1700,1600,1600,1600,1700,1700,1700,1700,1800,1900,2100,1900,2100
Southwark,1900,2200,2200,2000,2400,2600,2500,2400,2300,2900,3200,3500,3600,4000,4500,4800,5100
Sutton,600,600,600,600,600,600,600,600,600,600,700,700,600,600,700,700,800
Tower Hamlets,1300,1800,1900,1600,1700,1900,1900,1900,2200,2400,2800,3100,3300,4000,4600,5000,5200
Waltham Forest,500,500,500,400,500,400,500,500,400,500,600,600,600,600,700,900,1100
Wandsworth,1700,2000,2000,2000,1900,2100,2200,1800,2000,2500,2500,2500,2500,3000,3100,3200,3300
Westminster,20500,21600,22100,21700,22500,22800,22200,21600,21500,23400,24700,25700,27400,29900,30200,32300,33100